# Generated by Django 2.1.7 on 2020-07-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_text_info', models.CharField(default='', max_length=50, verbose_name='标题')),
                ('banner_image', models.ImageField(upload_to='banner/', verbose_name='轮播图')),
                ('banner_link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('banner_is_active', models.BooleanField(default=False, verbose_name='是否是active')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Blog_Type')),
                ('category_index', models.IntegerField(default=999, verbose_name='Type_Index')),
            ],
            options={
                'verbose_name': 'Blog_Type',
                'verbose_name_plural': 'Blog_Type',
            },
        ),
        migrations.CreateModel(
            name='Dragon_Article_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dragon_article_img', models.ImageField(blank=True, null=True, upload_to='article_image/%Y/%m/%d', verbose_name='Article_Images')),
                ('dragon_article_title', models.CharField(max_length=120, verbose_name='Title')),
                ('dragon_article_excerpt', models.TextField(blank=True, max_length=200, verbose_name='Excerpt')),
                ('dragon_article_content', models.TextField()),
                ('dragon_article_views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('dragon_article_publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Publicsh_Date')),
                ('dragon_article_update_date', models.DateTimeField(auto_now=True, verbose_name='Update_Date')),
                ('dragon_article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('dragon_article_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.Category', verbose_name='Blog_Type')),
            ],
            options={
                'verbose_name': 'Article_Post',
                'verbose_name_plural': 'Article_Post',
                'ordering': ('-dragon_article_update_date',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=20, verbose_name='链接名称')),
                ('link_url', models.URLField(max_length=100, verbose_name='网址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Recommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommand_name', models.CharField(max_length=100, verbose_name='Recommand_Space')),
            ],
            options={
                'verbose_name': 'Recommand_Space',
                'verbose_name_plural': 'Recommand_Space',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Article_Tag')),
            ],
            options={
                'verbose_name': 'Article_Tag',
                'verbose_name_plural': 'Article_Tag',
            },
        ),
        migrations.AddField(
            model_name='dragon_article_post',
            name='dragon_article_recommand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.Recommand', verbose_name='Recommand_Space'),
        ),
        migrations.AddField(
            model_name='dragon_article_post',
            name='dragon_article_tags',
            field=models.ManyToManyField(blank=True, to='Blog.Tag', verbose_name='Article_Tag'),
        ),
    ]
