# Generated by Django 2.1.7 on 2020-07-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dragon_article_post',
            options={'ordering': ('-dragon_article_publish_date',), 'verbose_name': 'Article_Post', 'verbose_name_plural': 'Article_Post'},
        ),
    ]
