# Generated by Django 2.1.7 on 2020-07-08 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200708_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '博文类别', 'verbose_name_plural': '博文类别'},
        ),
        migrations.AlterModelOptions(
            name='dragon_article_post',
            options={'ordering': ('-dragon_article_publish_date',), 'verbose_name': '文章发布', 'verbose_name_plural': '文章发布'},
        ),
        migrations.AlterModelOptions(
            name='recommand',
            options={'verbose_name': '推荐空间', 'verbose_name_plural': '推荐空间'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_index',
            field=models.IntegerField(default=999, verbose_name='类别索引'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='博文类别'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.Category', verbose_name='博客类别'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_img',
            field=models.ImageField(blank=True, null=True, upload_to='article_image/%Y/%m/%d', verbose_name='文章配图'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_publish_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_recommand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.Recommand', verbose_name='推荐空间'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_title',
            field=models.CharField(max_length=120, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='更改日期'),
        ),
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_views',
            field=models.PositiveIntegerField(default=0, verbose_name='访问量'),
        ),
        migrations.AlterField(
            model_name='recommand',
            name='recommand_name',
            field=models.CharField(max_length=100, verbose_name='推荐空间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=100, verbose_name='文章标签'),
        ),
    ]
