# Generated by Django 2.1.7 on 2020-07-08 03:39

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200708_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
