# Generated by Django 2.2 on 2020-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200708_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon_article_post',
            name='dragon_article_content',
            field=models.TextField(),
        ),
    ]
